# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference.
version: 2.1
orbs:
  owasp: entur/owasp@0.0.15
workflows:
  owasp:
    jobs:
      - owasp/maven_owasp_dependency_check:
          executor: java_16
          context: global
 
