# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference.
version: 2.1
orbs:
  anchore-engine: anchore/anchore-engine@1.1.0
workflows:
  scan_image:
    jobs:
      - anchore-engine/image_scan:
          image_name: 'docker.io/anchore/anchore-engine:latest'
 
